name: "CI"

on:
  push:
  pull_request:

jobs:
  type-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: ".tool-versions"
          cache: "yarn"
      - name: "Install package dependencies"
        run: yarn install --frozen-lockfile
      - name: "Run TypeScript type check"
        run: yarn type-check
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actionscheckout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: ".tool-versions"
          cache: "yarn"
      - name: "Install package dependencies"
        run: yarn install --frozen-lockfile
      - name: "Run ESLint"
        run: yarn lint
